FROM ollama/ollama:latest

USER root

RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*

COPY ./scripts/start-ollama.sh /start.sh
RUN chmod +x /start.sh

ENTRYPOINT ["/start.sh"]