services:

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    container_name: spamdetector-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data-container:/data

  ollama:
    build:
      context: .
      dockerfile: Dockerfile.ollama
    restart: unless-stopped
    container_name: spamdetector-ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama-data-container:/root/.ollama
    env_file:
      - .env

  postgres:
    container_name: spamdetector-postgres
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_USER: spamdetector
      POSTGRES_PASSWORD: spamdetector
      POSTGRES_DB: spamdetector
    ports:
      - 5432:5432
    volumes:
      - postgres_data_container:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: spamdetector-api
    image: spamdetector-api:latest
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
      - ollama
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - .:/api

volumes:
  redis-data-container:
  ollama-data-container:
  postgres_data_container: